input.onButtonPressed(Button.A, function () {
    wuKong.setLightMode(wuKong.LightMode.BREATH)
    wuKong.lightIntensity(100)
    wuKong.setAllMotor(0, -50)
    basic.pause(2000)
    wuKong.lightIntensity(50)
    wuKong.setAllMotor(0, 50)
    basic.pause(2000)
    wuKong.lightIntensity(0)
    wuKong.stopMotor(wuKong.MotorList.M2)
})
input.onButtonPressed(Button.AB, function () {
    wuKong.lightIntensity(100)
    wuKong.setAllMotor(100, 0)
    basic.pause(2000)
    wuKong.lightIntensity(0)
    wuKong.stopMotor(wuKong.MotorList.M1)
})
input.onButtonPressed(Button.B, function () {
    wuKong.setAllMotor(-100, 0)
    wuKong.lightIntensity(100)
    basic.pause(2000)
    wuKong.lightIntensity(0)
    wuKong.stopMotor(wuKong.MotorList.M1)
})
